# Generated by Django 3.2.21 on 2023-09-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='highlight',
            field=models.CharField(max_length=250),
        ),
    ]
