# Generated by Django 3.2.21 on 2023-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_dish_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@example.com', editable=False, max_length=254),
        ),
    ]
