# Generated by Django 3.2.21 on 2023-10-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
